== Overview and Summary of Contributions
The goal of this work was to develop a unified framework for analyzing genomic interval data -- particularly single-cell ATAC-seq (scATAC-seq) -- through modern machine learning and transfer learning. This was achieved through three key contributions that together form a scalable and interpretable foundation and framework for chromatin accessibility analysis through democratized deep learning models. At its core, this dissertation conceptualizes genomic regions as discrete, linguistic tokens, adapting natural language processing (NLP) concepts and modeling strategies to epigenomics. This, in turn, develops infrastructure and subsequent foundation models that learn generalizable regulatory representations transferable across datasets and biological contexts.

First, we developed high-performance infrastructure for data preprocessing and standardization called the `gtars` toolkit. Written in Rust with Python bindings, gtars provides efficient handling of large-scale genomic interval data and utilities for two key tasks: first, defining region universes from large collections of peak calls, and second, tokenizing individual datasets against these universes. This infrastructure facilitates consistent data representation by ensuring that all datasets share a common vocabulary of genomic regions, which is critical for enabling transfer learning in downstream models. Furthermore, gtars' performance and usability lower the barrier to entry for researchers seeking to apply machine learning to chromatin accessibility data, as well as ensuring that these tools fit into the broader machine learning ecosystem.

Second, we introduced scEmbed, a Word2Vec-inspired model demonstrating that pre-trained region embeddings can be reused across datasets. Trained on large chromatin accessibility corpora, scEmbed learns fixed embeddings for genomic regions that encode shared regulatory context. These embeddings enable rapid analysis and transferability across studies without retraining, establishing the feasibility and importance of stable, shared token vocabularies in genomic modeling. However, scEmbed's static embeddings revealed limitations in small, static representations that failed to generalize to cell-state-specific regulatory dynamics, motivating the need for larger, more flexible models capable of contextual understanding.

Finally, to address these limitations, we developed Atacformer, the central contribution that realizes the core vision of this work: a transformer-based foundation model that generates contextualized region embeddings by incorporating cell-level chromatin accessibility context. Atacformer captures complex regulatory dependencies and generalizes across biological conditions, performing well in zero-shot settings for clustering, annotation, and batch correction. In parallel, we introduced the CRAFT model, a dual-encoder architecture linking Atacformer with Geneformer to jointly model chromatin accessibility and gene expression, illustrating the potential for unified multiomic embeddings that was envisioned from the beginning of this research program. We finally explored the biological insights enabled by these models, demonstrating that they capture meaningful regulatory relationships, identify cryptic promoters, and reflect functional relatedness among genomic regions, highlighting the models interpretability and biological relevance.

Together, these components form a continuous pipeline from disparate, raw genomic intervals to contextual representations, which is anchored in shared vocabulary, interpretability, and scalability.