== Overview and Summary of Contributions
The goal of this work was to develop a unified framework for analyzing genomic interval data — particularly single-cell ATAC-seq (scATAC-seq) — through modern machine learning and transfer learning. This was achieved through three key contributions that together form a scalable and interpretable foundation for chromatin accessibility analysis. At its core, this dissertation conceptualizes genomic regions as discrete, linguistic, tokens, enabling the direct adaptation of natural language processing (NLP) concepts and modeling strategies to epigenomics.

First, we developed high-performance infrastructure for data preprocessing and standardization through the `gtars` toolkit. Written in Rust with Python bindings, gtars provides efficient handling of large-scale genomic interval data and utilities for defining region universes and tokenizing intervals. This framework transforms disparate, experiment-specific peak calls into a consistent vocabulary suitable for model training and transfer learning.

Second, we introduced scEmbed, a Word2Vec-inspired model demonstrating that pre-trained region embeddings can be reused across datasets. Trained on large chromatin accessibility corpora, scEmbed learns fixed embeddings for genomic regions that encode shared regulatory context. These embeddings enable rapid analysis and transferability across studies without retraining, establishing the feasibility and importance of stable, shared token vocabularies in genomic modeling.

Finally, we developed Atacformer, the central contribution that realizes the core vision of this work: a transformer-based foundation model that generates contextualized region embeddings by incorporating cell-level chromatin accessibility context. Atacformer captures complex regulatory dependencies and generalizes across biological conditions, performing well in zero-shot settings for clustering, annotation, and batch correction. In parallel, we introduced the CRAFT model, a dual-encoder architecture linking Atacformer with Geneformer to jointly model chromatin accessibility and gene expression, illustrating the potential for unified multiomic embeddings that was envisioned from the beginning of this research program.

Together, these components form a continuous pipeline from disparate, raw genomic intervals to contextual representations, which is anchored in shared vocabulary, interpretability, and scalability.
