Chromatin accessibility profiling is a powerful approach for understanding gene regulation -- a key determinant of cellular identity and function. Despite the existence of nearly 10,000 publicly available scATAC-seq experiments, unifying all of this data for meaningful downstream analysis remains a significant challenge. While existing tools adequately handle basic single-cell chromatin accessibility analysis, they are not architected to leverage modern deep learning approaches that could unlock insights across biological contexts and enable integration into advanced analytical workflows at scale.

Recent advances in machine learning suggest a path forward. Transfer learning, particularly with large pre-trained models, has shown promise in scRNA-seq applications by enabling improved cell type clustering, identification, and dataset integration across studies. However, the application of transfer learning to scATAC-seq remains underexplored, despite similar structural and analytical challenges shared between the modalities.

This dissertation explores transformer-based transfer learning approaches tailored for scATAC-seq data. We present a suite of deep learning tools and frameworks that leverage large public datasets to improve the analysis of new, unseen experiments. Across multiple benchmarks, these approaches demonstrate improved computational efficiency, strong performance, and discovery of biological insights, laying the groundwork for scalable, standardized analysis of chromatin accessibility data.

In Chapter 1, we review the current landscape of gene regulation and scATAC-seq analysis, detailing existing workflows, their limitations, and the growing interest in developing general-purpose foundation models for chromatin data interpretation.

In chapter 2, we provide essential background on natural language processing (NLP) techniques, focusing on transformer architectures and self-supervised learning methods that have revolutionized text analysis. We discuss how these concepts can be adapted to genomic data, highlighting parallels between language and genomic regulatory regions.

In Chapter 3, we describe `gtars`: a library of supporting infrastructure for high-throughput, efficient scATAC-seq data processing to generate model vocabularies and perform tokenization on new datasets. This includes Rust-based genomic tokenizers for rapid interval processing and `uniwig`: a tool for consensus set generation. We demonstrate how these tools facilitate scalable data handling for downstream machine learning applications.

In Chapter 4, we extend prior work on self-supervised representation learning of bulk ATAC-seq data by adapting the framework to the single-cell setting with a new model called scEmbed. We introduce early transfer learning pipelines that use genomic region embeddings as input for downstream scATAC-seq tasks, forming a foundation for generalizable and sharable models. We highlight how pretrained embeddings can be leveraged to improve clustering speed and accuracy, as well as enable cross-dataset cell type annotation.

In Chapter 5, we introduce Atacformer, a transformer-based model specifically designed to learn contextualized representations of genomic interval data. Atacformer builds on scEmbed by introducing self-attention mechanisms to capture contextual dependencies within chromatin accessibility profiles. We describe its architecture, training strategy, and application to tasks such as clustering, annotation, and multiomic integration, showing how it benefits from pretraining and transfer learning. We finally show how Atacformer can be used to discover biological insights such as weak promoter elements.

In Chapter 6, we outline the limitations of our approach and identify key directions for future work. These include better benchmarking standards, refining tokenization strategies to improve generalization and interpretability, and algorithmic improvements to enable easier model training and deployment on diverse computing environments.

Together, these chapters provide a comprehensive framework for applying modern machine learning techniques to scATAC-seq analysis, with a focus on flexible, transferable models that bridge the gap between isolated experiments and unified biological insight.