=== The high-dimensionality and inherent sparsity of scATAC-seq data
While scATAC-seq has opened new avenues for understanding gene regulation, it also presents unique challenges, such as increased technical variability and the need for specialized computational tools to analyze the resulting data. Addressing these challenges will be crucial for fully realizing the potential of single-cell epigenomics in uncovering the complexities of gene regulation.

A scATAC-seq dataset is often represented as a binary matrix where rows correspond to cells, and columns correspond to genomic loci (@scatac-seq-overview). These matrices are characterized by their high dimensionality and inherent sparsity, posing significant challenges for computational analysis. Because each cell only contains two copies of each chromosome, and because the assay measures accessibility at upwards of 1 million genomic loci, the resulting data matrix is often extremely sparse and high-dimensional. It is not uncommon for matrices to exceed a hundred thousand rows and one million columns with only a small fraction of the entries filled. This sparsity can make it difficult to accurately infer regulatory interactions and identify cell-type-specific patterns of chromatin accessibility. Furthermore, the high dimensionality of scATAC-seq data can make traditional statistical methods less effective @Cusanovich2015 while simultaneously presenting significant computational challenges.

#figure(
  image("/fig/introduction/scatac-seq.svg"),
  caption: [Schematic of a scATAC-seq count matrix.]
) <scatac-seq-overview>

To address these challenges, researchers have developed new computational methods and tools specifically designed for scATAC-seq data. These approaches aim to improve data normalization, enhance signal detection, and facilitate the integration of scATAC-seq data with other single-cell modalities, such as scRNA-seq. By leveraging advances in machine learning and statistical modeling, these methods hold promise for unlocking the full potential of single-cell epigenomics in understanding gene regulation.

=== Traditional single-cell ATAC-seq analysis methods
Soon after the onset of scATAC-seq, several computational tools were developed to address the unique challenges posed by the data modality. Among those were BROCKMAN @DeBoer2018, chromVAR @Schep2017, Cicero @Pliner2018, SCRAT @Ji2017a, cisTopic @BravoGonzález-Blas2019, EpiScanpy @Danese2021, and SnapATAC @Fang2021a. Each of these tools employs distinct strategies to extract regulatory and cell-type information.

==== Peak-based variability analysis: chromVAR
chromVAR focuses on estimating the variability of chromatin accessibility across peaks that share common features, such as transcription factor motifs or specific k-mers. This method enables researchers to identify regulatory elements that show differential accessibility across cell types or conditions by leveraging known sequence motifs and annotations. By computing deviation scores for each motif in each cell, chromVAR provides insights into the activity of specific transcription factors across single-cell profiles.

==== Sequence-based dimensionality reduction: BROCKMAN
BROCKMAN represents genomic sequences using gapped k-mers within transposase integration sites and applies principal component analysis (PCA) to capture variation in k-mer occupancy. This approach bypasses the need for peak calling by directly analyzing the sequence context of ATAC-seq insertions. The method's focus on k-mer patterns allows it to capture regulatory signals that might be missed by peak-centric approaches, providing a complementary perspective on chromatin accessibility patterns.

==== Gene activity scoring and regulatory networks: Cicero
Cicero leverages and estimates gene activity scores at each peak by computing accessibility at promoters with the regulatory potential of nearby peaks. This method goes beyond simple accessibility measurements by attempting to link distal regulatory elements to their target genes through co-accessibility analysis. Cicero constructs regulatory networks by identifying peaks that are frequently accessible together, enabling the prediction of gene regulatory relationships and the identification of putative enhancer-promoter interactions.

==== Topic modeling approaches: cisTopic
cisTopic uses latent Dirichlet allocation (LDA), a Bayesian topic modeling method originally developed for natural language processing, to simultaneously uncover cell states and putative regulatory regions. In this framework, cells are treated as documents and accessible regions as words, allowing the method to identify "topics" that represent co-accessible regulatory programs. This probabilistic approach enables the discovery of regulatory modules and cell types while providing interpretable results about the underlying regulatory architecture.

==== Latent semantic indexing approaches
Another class of approaches, which follow the Cusanovich2018 pipeline, employs latent semantic indexing (LSI). These methods begin by partitioning the genome into windows, normalizing read counts using the term frequency–inverse document frequency (TF-IDF) transformation. Dimensionality is then reduced using singular value decomposition (SVD), and a first round of clustering—termed "in silico cell sorting"—is performed to identify clades and call peaks within them. A second round of TF-IDF and SVD is applied using read counts in the called peaks to refine the clusters. This iterative approach combines dimensionality reduction with peak calling to improve both cell clustering and regulatory region identification.

==== Bin-based analysis with regression normalization: SnapATAC
SnapATAC segments the genome into uniform bins and corrects for library size differences using regression-based normalization, followed by PCA to identify key components for clustering analysis. Unlike peak-based methods, this approach avoids potential biases introduced by peak calling algorithms by analyzing accessibility in fixed genomic windows. The regression-based normalization specifically addresses technical confounders such as sequencing depth and mitochondrial read fraction, making it particularly robust for large-scale comparative analyses.

=== End-to-end pipelines and more recent methods
Still, more methods have continued to emerge, incorporating more robust statistical frameworks, end-to-end pipelines, and novel algorithms for dimensionality reduction, clustering, and visualization. Examples of this include ArchR @Granja2021: a comprehensive software suite for end-to-end analysis of single-cell chromatin accessibility written in R, Signac @Stuart2021: an extension of the Seurat framework for the analysis of single-cell chromatin data, and SnapATAC2 @Zhang2024: a rust-based package for fast, memory-efficient analysis of scATAC-seq data that leverages a novel spectral embedding dimensionality reduction algorithm. SnapATAC2, in particular was one of the first python-native tools for scATAC-seq, targeting atlas-scale datasets with millions of cells.

Together, these tools have significantly advanced the field of single-cell epigenomics, enabling extraction of meaningful biological insights from complex scATAC-seq datasets. Researchers now have access to a diverse array of computational resources in many programming languages and environments, facilitating the study of gene regulation at single-cell resolution. As the field continues to mature and evolve, this has paved the way for more sophisticated methods, including deep learning-based approaches to extract even more intricate patterns of chromatin accessibility.
