As deep learning revolutionizes fields like computer vision (CV) and natural language processing (NLP), researchers are exploring its application to single-cell genomics, including scATAC-seq analysis. Deep learning models, particularly those based on neural networks, show promise in capturing complex patterns and relationships within high-dimensional data. The computational methods developed for scATAC-seq analysis can be conceptually organized into two primary paradigms based on their underlying modeling strategy: (1) generative models that learn latent representations of chromatin accessibility patterns from peak-by-cell matrices, exemplified by SCALE and PeakVI; and (2) sequence-based discriminative models that leverage DNA sequence information to predict accessibility, as demonstrated by scBasset. These complementary approaches address different aspects of the scATAC-seq analysis challenge and offer distinct advantages for understanding cellular heterogeneity and regulatory mechanisms.

=== Generative modeling approaches
Generative models for scATAC-seq data learn probabilistic representations of chromatin accessibility by modeling the underlying distribution of peak-by-cell observations. These methods employ variational inference frameworks to capture complex dependencies in the data while enabling dimensionality reduction, denoising, and clustering.

==== SCALE: A variational autoencoder for scATAC-seq
One of the first deep learning methods developed for scATAC-seq data was SCALE @Xiong2019, which employs a deep generative model to learn a low-dimensional representation of scATAC-seq data. SCALE uses a variational autoencoder (VAE) architecture to model the underlying distribution of chromatin accessibility profiles, enabling effective dimensionality reduction and clustering of cells based on their accessibility patterns. SCALE takes as input a binarized peak-by-cell matrix and learns a latent representation that captures the key features of the data while accounting for technical noise and variability. The model is trained using a combination of reconstruction loss and a regularization term that encourages the latent space to follow a prior distribution, typically a standard normal distribution. This approach allows SCALE to effectively denoise the data and identify meaningful biological variation among cells.

==== PeakVI: A variational inference model with batch correction
Building on the generative modeling framework established by SCALE, PeakVI introduces explicit handling of technical variation and batch effects while decomposing accessibility observations into interpretable components. This method leverages variational inference with deep neural networks to model scATAC-seq data by decomposing chromatin accessibility observations into three key components @Ashuach2022. PeakVI employs a variational autoencoder architecture where an encoder network infers latent representations from observed data, a decoder network generates accessibility probability estimates, and auxiliary neural networks estimate region-specific scaling factors. This approach enables batch correction, normalized visualization, and clustering while providing interpretable estimates of the true chromatin landscape by separating biological signal from technical confounders.

=== Sequence-based discriminative approaches
While generative models learn from observed accessibility patterns, sequence-based approaches leverage the DNA sequence itself as input, enabling predictions for arbitrary genomic regions and capturing sequence-specific regulatory logic.

==== scBasset: A convolutional neural network for sequence-based chromatin accessibility
Representing a fundamentally different modeling paradigm, scBasset @Yuan2022 leverages a convolutional neural network (CNN) architecture to learn sequence-based representations of chromatin accessibility. scBasset is trained on the actual DNA sequences underlying accessible regions, allowing it to capture sequence motifs and patterns associated with regulatory elements. This approach enables improved prediction of chromatin accessibility and identification of cell-type-specific regulatory features. One key advantage of scBasset is its ability to analyze new, unseen genomic regions based on their sequence content, making it more flexible and generalizable compared to methods that rely solely on predefined peak sets. The model is trained using a binary cross-entropy loss function, optimizing the network to accurately predict accessibility status based on sequence input.

=== Limitations of current approaches
While these methods demonstrate the power of deep learning for scATAC-seq analysis, they also face important limitations that constrain their applicability. SCALE is designed to be retrained with each new dataset, limiting its ability to generalize across experiments and requiring substantial computational resources for each analysis. scBasset, while leveraging sequence information to enable predictions on novel genomic regions, does not directly model cell-to-cell variability in accessibility profiles, which is a fundamental characteristic of single-cell data. PeakVI addresses batch effects more explicitly than SCALE but still requires dataset-specific training. Moreover, all of these methods require substantial computational resources for both training and inference, which can be a barrier for widespread adoption. These limitations highlight the need for more flexible and efficient approaches to scATAC-seq analysis that can generalize across datasets while still leveraging the representational power of deep learning.