=== Why does the same DNA makes different cells?
Inside the nucleus of all 30 trillion of our cells is about six feet of DNA tightly packed and coiled up into compact structures called chromosomes @Alberts2002. Remarkably, this DNA sequence is nearly identical across all cell types within an individual, yet it gives rise to extraordinary levels of heterogeneity in cell types, tissues, disease states, and physiological responses. This fundamental paradox raises a critical question: _how does a single, static genetic blueprint generate such diverse biological outcomes_?

While the DNA sequence itself is largely invariant across cell types, its interpretation is highly dynamic and context-specific. Cells achieve this through complex layers of gene regulation, which govern when, where, and to what extent specific genes are transcribed into RNA. At the heart of this regulatory machinery are elements like promoters, which initiate transcription near gene start sites, and enhancers, which can activate transcription at distant genomic loci in a cell-type–specific manner. These elements recruit combinations of transcription factors, cofactors, and RNA polymerases to modulate gene expression. Importantly, these interactions are influenced by the chromatin landscape, which determines the physical accessibility of DNA to regulatory proteins. Thus, biological heterogeneity arises not only from differences in genetic code but from the selective and combinatorial usage of regulatory elements across different cell types, developmental stages, and environmental conditions.

#figure(
  image("../../fig/chapter1/gene-regulation.svg"),
  caption: [A schematic representation of gene regulation, highlighting the roles of promoters, enhancers, and the chromatin landscape in modulating gene expression.]
)

=== The rise of epigenomics assays
The completion of the Human Genome Project @Lander2001 enabled the development of various 'omics technologies to investigate this phenomenon. Simultaneously, genome-wide association studies (GWAS) revealed that approximately 90% of disease-associated single nucleotide polymorphisms (SNPs) are located in non-coding regions of the genome, highlighting the crucial importance of studying gene regulation and epigenomics in human health and disease for driving this biological heterogeneity @Farh2015 @French2020. This discovery catalyzed the development of technologies to study regulatory elements, including DNA methylation analysis through bisulfite sequencing @Frommer1992 @Li2011, chromatin immunoprecipitation sequencing (ChIP-seq) @Robertson2007, DNase hypersensitivity sequencing (DNase-seq) @Boyle2008, and the Assay for Transposase-Accessible Chromatin using sequencing (ATAC-seq) @Buenrostro2013, with modern single-cell variants now available for many approaches @Rotem2015 @Smallwood2014 @Buenrostro2015.

ATAC-seq has gained widespread adoption due to its technical quality and economic advantages, but this popularity has brought numerous computational and analytical challenges in studying the resulting data.