=== The high-dimensionality and inherent sparsity of scATAC-seq data
A scATAC-seq dataset is often represented as a binary matrix where rows correspond to cells, and columns correspond to genomic loci (@scatac-seq-overview). These matrices are characterized by their high dimensionality and inherent sparsity, posing significant challenges for computational analysis. Because each cell only contains two copies of each chromosome, and because the assay measures accessibility at upwards of 1 million genomic loci, the resulting data matrix is often extremely sparse and high-dimensional. This sparsity can make it difficult to accurately infer regulatory interactions and identify cell-type-specific patterns of chromatin accessibility. Furthermore, the high dimensionality of scATAC-seq data can make traditional statistical methods less effective @Cusanovich2015.

#figure(
  image("../../fig/introduction/scatac-seq.svg"),
  caption: [Schematic of a scATAC-seq count matrix.]
) <scatac-seq-overview>

To address these challenges, researchers have developed new computational methods and tools specifically designed for scATAC-seq data. These approaches aim to improve data normalization, enhance signal detection, and facilitate the integration of scATAC-seq data with other single-cell modalities, such as scRNA-seq. By leveraging advances in machine learning and statistical modeling, these methods hold promise for unlocking the full potential of single-cell epigenomics in understanding gene regulation.

=== Traditional single-cell analysis methods
Soon after the onset of scATAC-seq analysis, several computational tools were developed to address the unique challenges posed by the data modality. Among those were BROCKMAN @DeBoer2018, chromVAR @Schep2017, Cicero @Pliner2018, SCRAT @Ji2017a, cisTopic @BravoGonzález-Blas2019, and SnapATAC @Fang2021a. Each of these tools employs distinct strategies to extract regulatory and cell-type information.

Briefly, chromVAR focuses on estimating the variability of chromatin accessibility across peaks that share common features, such as transcription factor motifs or specific k-mers. BROCKMAN represents genomic sequences using gapped k-mers within transposase integration sites and applies principal component analysis (PCA) to capture variation in k-mer occupancy. Cicero leverages and estimated gene activity score at each peak by integrating accessibility at promoters with the regulatory potential of nearby peaks. cisTopic uses latent Dirichlet allocation (LDA), a Bayesian topic modeling method originally developed for natural language processing, to simultaneously uncover cell states and putative regulatory regions. Another class of approaches, which follow the Cusanovich2018 pipeline, employs latent semantic indexing (LSI). These methods begin by partitioning the genome into windows, normalizing read counts using the term frequency–inverse document frequency (TF-IDF) transformation. Dimensionality is then reduced using singular value decomposition (SVD), and a first round of clustering—termed “in silico cell sorting”—is performed to identify clades and call peaks within them. A second round of TF-IDF and SVD is applied using read counts in the called peaks to refine the clusters. Lastly, SnapATAC segments the genome into uniform bins and corrects for library size differences using regression-based normalization, followed by PCA to identify key components for clustering analysis.

Still more methods have continued to emerge, incorporating more robust statistical frameworks, end-to-end pipelines, and novel algorithms for dimensionality reduction, clustering, and visualization. Examples of this include ArchR @Granja2021, a comprehensive software suite for end-to-end analysis of single-cell chromatin accessibility written in R, Signac @Stuart2021, an extension of the Seurat framework for the analysis of single-cell chromatin data, and SnapATAC2 @Zhang2024, a rust-based package for fast, memory-efficient analysis of scATAC-seq data that leverages a novel spectral embedding dimensionality reduction algorithm.

Together, these tools have significantly advanced the field of single-cell epigenomics, enabling extraction of meaningful biological insights from complex scATAC-seq datasets. Researchers now have access to a diverse array of computational resources in many programming languages and environments, facilitating the study of gene regulation at single-cell resolution. As the field continued to mature and evolve, this paved the way for more sophisticated methods, including deep learning-based approaches extract even more intricate patterns of chromatin accessibility.

=== Deep learning-based methods for scATAC-seq analysis
As deep learning revolutionized fields like computer vision (CV) and natural language processing (NLP), researchers began exploring its application to single-cell genomics, including scATAC-seq analysis. Deep learning models, particularly those based on neural networks, have shown promise in capturing complex patterns and relationships within high-dimensional data.

One of the first methods developed was SCALE @Xiong2019, which employs a deep generative model to learn a low-dimensional representation of scATAC-seq data. SCALE uses a variational autoencoder (VAE) architecture to model the underlying distribution of chromatin accessibility profiles, enabling effective dimensionality reduction and clustering of cells based on their accessibility patterns.

Another notable method is scBasset @Yuan2022, which leverages a convolutional neural network (CNN) architecture to learn sequence-based representations of chromatin accessibility. scBasset is trained on DNA sequences underlying accessible regions, allowing it to capture sequence motifs and patterns associated with regulatory elements. This approach enables improved prediction of chromatin accessibility and identification of cell-type-specific regulatory features.

While powerful, these methods also face challenges. Namely, SCALE is designed to be retrained with each new dataset, limiting its ability to generalize across experiments. scBasset, while leveraging sequence information, does not directly model cell-to-cell variability in accessibility profiles, which is a key aspect of single-cell data. Moreover, all of these methods require substantial computational resources for both training and inference, which can be a barrier for widespread adoption.

These limitations highlight the need for more flexible and efficient approaches to scATAC-seq analysis that still leverage the power of deep learning.

// === Large, pre-trained foundation models
