As deep learning revolutionizes fields like computer vision (CV) and natural language processing (NLP), researchers are exploring its application to single-cell genomics, including scATAC-seq analysis. Deep learning models, particularly those based on neural networks, show promise in capturing complex patterns and relationships within high-dimensional data.

One of the first methods developed was SCALE @Xiong2019, which employs a deep generative model to learn a low-dimensional representation of scATAC-seq data. SCALE uses a variational autoencoder (VAE) architecture to model the underlying distribution of chromatin accessibility profiles, enabling effective dimensionality reduction and clustering of cells based on their accessibility patterns.

Another notable method is scBasset @Yuan2022, which leverages a convolutional neural network (CNN) architecture to learn sequence-based representations of chromatin accessibility. scBasset is trained on the actual DNA sequences underlying accessible regions, allowing it to capture sequence motifs and patterns associated with regulatory elements. This approach enables improved prediction of chromatin accessibility and identification of cell-type-specific regulatory features.

Even more recently is PeakVI. This method leverages variational inference with deep neural networks to model scATAC-seq data by decomposing chromatin accessibility observations into three key components @Ashuach2022. PeakVI employs a variational autoencoder architecture where an encoder network infers latent representations from observed data, a decoder network generates accessibility probability estimates, and auxiliary neural networks estimate region-specific scaling factors. This approach enables batch correction, normalized visualization, and clustering while providing interpretable estimates of the true chromatin landscape by separating biological signal from technical confounders.

While powerful, these methods also face challenges. Namely, SCALE is designed to be retrained with each new dataset, limiting its ability to generalize across experiments. scBasset, while leveraging sequence information, does not directly model cell-to-cell variability in accessibility profiles, which is a key aspect of single-cell data. Moreover, all of these methods require substantial computational resources for both training and inference, which can be a barrier for widespread adoption.

These limitations highlight the need for more flexible and efficient approaches to scATAC-seq analysis that still leverage the power of deep learning.