=== Future aim 3: Token-level interpretability and fine-tuning

==== Motivation
While Atacformer demonstrates strong performance on cell-level tasks such as clustering and annotation, interpretation and analysis of contextualized region embeddings remains underdeveloped. Our initial exploration of token-level embeddings revealed promising signals. For instance, we identified putative latent transcription start sites within weak promoter regions by examining how these regions cluster in embedding space to reveal paradoxic patterns: regions annotated as being far from transcription start sites while clustering with known TSSs (@atacformer-ictss). However, we have only scratched the surface of what token-level analysis could reveal about regulatory grammar and chromatin organization. Two complementary directions could substantially advance our understanding: attention-based relationship discovery and token-level fine-tuning for region annotation tasks.

==== Proposed approach: Attention matrix analysis
Transformer attention matrices encode pairwise relationships between tokens, and attention weight analysis has proven valuable in natural language processing for uncovering syntactic dependencies and semantic relationships @Vig2019 @Vashishth2019. In genomics, attention patterns could reveal functional regulatory connections that are not apparent from sequence features alone. We propose systematic extraction and analysis of attention weights between region pairs across large cohorts of cells. Consistently high-attention pairs across diverse cell types would suggest stable regulatory interactions, such as housekeeping promoter-enhancer links, while cell-type-specific attention patterns could identify dynamic, context-dependent regulatory wiring. These attention-derived relationships could be used to predict promoter-enhancer pairs, infer transcription factor co-binding networks, and identify compensatory or redundant regulatory elements. Validation against orthogonal data sources like Hi-C contact maps, ChIA-PET loops, and expression quantitative trait loci (eQTLs) would assess whether attention weights capture biologically meaningful three-dimensional chromatin interactions and regulatory logic.

==== Proposed approach: Token-level fine-tuning
In our current work, we explored fine-tuning strategies exclusively at the cell level, training models to predict cellular phenotypes or cluster assignments. However, token-level fine-tuning—analogous to named entity recognition (NER) in natural language processing—remains unexplored and could unlock new capabilities @Devlin2019a @Li2020. One compelling application would be training models to predict chromatin contact pairs using small Hi-C datasets as supervision. This would create a generative model capable of predicting topologically associating domains (TADs) and long-range interactions directly from scATAC-seq data, effectively learning to infer three-dimensional genome organization from accessibility patterns alone. Another promising direction involves region annotation tasks, where the model learns to classify individual regions (e.g., as active enhancers, silencers, or insulators) based on the broader regulatory context of the cell. This context-aware annotation would differ fundamentally from static chromatin state annotations like ChromHMM, as it would account for the dynamic regulatory environment captured by the full set of accessible regions in each cell. Both applications would leverage the rich contextual information encoded in Atacformer's learned representations, extending the model's utility beyond cell-level predictions to region-level biological insights.

==== Expected impact
These advances would yield two major benefits. First, token-level analysis would provide mechanistic insights into regulatory grammar that are currently inaccessible—revealing novel promoter-enhancer wiring, identifying context-dependent regulatory switches, and generating testable hypotheses about three-dimensional genome organization. Second, fine-tuned models for contact prediction and region annotation could be released as community resources, enabling researchers to leverage foundation model representations for specific biological questions without requiring computational expertise or large-scale datasets. By extending capabilities from cell-level clustering to region-level insights, these directions would democratize sophisticated regulatory genomics analysis.
