=== scEmbed model architecture and training
We used the `gensim` python implementation of Word2Vec as the core model for scEmbed. Word2Vec has many configurable hyperparameters @Mikolov2013a, including context window size, embedding size, learning rate scheduling and number of epochs. All experiments were conducted with a fixed set of hyperparameters. We used defaults for scEmbed, informed by experiments on Region2Vec optimization @Zheng2024. Specifically, we use a window size of 5 and an embedding dimension of 100. We also use 100 epochs for all experiments unless otherwise noted. We adopt an exponential learning rate schedule with a decay rate of 0.95. After training, we extract the learned region embeddings from the Word2Vec model and subsequently transfer them to an equivalent model in `pytorch`. This improves accessibility and interoperability with other deep learning frameworks.

To tokenize cells, we use our previously designed genomic tokenizers. Briefly, we take an individual cell and identify each region where it shows signal. We define signal as anything greater than zero. These regions are then collected and we use interval overlap arithmetic to create a set of tokenized genomic intervals for each cell. These tokens are then shuffled and fed into the Word2Vec model for training.

=== scEmbed model benchmarking and evaluation <scembed-benchmarking-methods>
To validate scEmbed, we followed an earlier approach @Chen2019a to benchmark it on clustering tasks using published reference scATAC data. We leveraged four main datasets in this work: 1) the Buenrostro2018 dataset, single-cell chromatin accessibility profiles from 10 human hematopoietic cell types @Buenrostro2018; 2) Luecken2021, a multimodal single-cell benchmarking dataset of 120,000 single cells from the human bone marrow of 10 diverse donors measured with two commercially available multimodal technologies @Luecken2021; 3) 10X genomics 5k PBMCs, a single-cell dataset of 5000 peripheral blood mononuclear cells from a healthy donor; and 4) a synthetic bone marrow dataset, a binary accessibility dataset described and provided by Chen et al. @Chen2019a.

We benchmarked scEmbed on the Buenrostro2018 dataset @Buenrostro2018 as well as a more recent and comprehensive scATAC-seq dataset from Luecken2021 @Luecken2021. We trained scEmbed for 100 epochs (TODO) then used the resulting region embeddings to construct cell embeddings. Following previous benchmarking procedures, we clustered the cell embeddings with three clustering methods: K-means, hierarchical clustering (HC), and Louvain clustering. There are two scenarios for which we can evaluate clustering: known ground-truth labels and unknown ground-truth labels. The synthetic bone marrow, Buenrostro2018, and Luecken2021 datasets have known ground-truth labels while the PBMC data have unknown ground-truth labels. When ground-truth labels are known, we employ three scores: the adjusted rand index (ARI), the adjusted mutual info score (AMI), and the homogeneity score. When ground-truth labels are not known, we use the Residual Average Gini Index (RAGI) @Chen2019a

=== Dropout experiments
To explore its transfer learning ability and test robustness to missing data, following Xiong et al. @Xiong2019, we evaluated scEmbed on datasets with increasing levels of information loss. Starting from the already sparse Buenrostro2018 cell-feature matrix (2.8% non-zero) @Rymuza2024, we randomly dropped non-zero values in the binary accessibility matrix until ∼80% of the non-zero data were lost, resulting in a matrix that was 0.5% non-zero